// Re-export FontAwesome component and commonly used icons for the app
export { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
export {
  faBars,
  faCheck,
  faChevronUp,
  faComments,
  faDisplay,
  faHashtag,
  faLock,
  faMicrophone,
  faMicrophoneSlash,
  faPaperPlane,
  faPhoneSlash,
  faPlus,
  faRightFromBracket,
  faSearch,
  faSignOutAlt,
  faSpinner,
  faStop,
  faSync,
  faTimes,
  faUser,
  faVideo,
  faVideoSlash,
  faVolumeHigh,
  faWindowMaximize,
  faVolumeLow,
  faVolumeXmark,
  faXmark,
  faMusic,
  faCircleExclamation,
  faWaveSquare,
} from '@fortawesome/free-solid-svg-icons'
export { faEye, faEyeSlash, faUser as faUserOutline } from '@fortawesome/free-regular-svg-icons'
